language: node_js
sudo: false
cache:
  yarn: true
  directories:
  - node_modules
node_js:
- stable
- '8'
- '6'
deploy:
  skip_cleanup: true
  provider: npm
  email: lindarian12@gmail.com
  api_key: $NPM_API_KEY
  on:
    tags: true
    repo: ramoona/banks-db
